# not used

import re
import argparse
import os

# 1. Go 类型到 SQLite 类型映射
GO_SQL_TYPE_MAP = {
    "string": "TEXT",
    "int": "INTEGER",
    "int8": "INTEGER",
    "int16": "INTEGER",
    "int32": "INTEGER",
    "int64": "INTEGER",
    "uint": "INTEGER",
    "uint8": "INTEGER",
    "uint16": "INTEGER",
    "uint32": "INTEGER",
    "uint64": "INTEGER",
    "float32": "REAL",
    "float64": "REAL",
    "bool": "INTEGER", # SQLite uses 0 or 1 for boolean
    "[]byte": "BLOB",
    # Add more mappings as needed, e.g., time.Time to TEXT or INTEGER (Unix timestamp)
    # "time.Time": "TEXT",
}

# 2. 解析 Go 结构体
def parse_go_struct(file_path):
    """
    解析 Go 文件，提取 Record 结构体的字段信息。
    返回 (package_name, struct_name, [(field_name, go_type, json_tag, is_pk), ...], pk_field_info)
    """
    package_name = ""
    struct_name = ""
    fields = []
    in_struct = False
    pk_field_info = None  # (field_name, go_type, json_tag)

    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    for line in lines:
        line = line.strip()

        if line.startswith("package "):
            package_name = line.split(" ")[1]

        if line.startswith("type ") and " struct {" in line:
            match = re.match(r"type (\w+) struct {", line)
            if match:
                struct_name = match.group(1)
                if struct_name == "Record": # We are specifically looking for "Record"
                    in_struct = True
                    continue

        if in_struct:
            if line == "}":
                in_struct = False
                break
            
            # Match field: FieldName Type `json:"tag"`
            # This regex is robust for typical Go struct field definitions.
            match = re.match(r"(\w+)\s+(\S+)\s*(`[^`]*`)*", line)
            if match:
                field_name = match.group(1)
                go_type = match.group(2)
                raw_tag = match.group(3) if match.group(3) else ""
                
                json_tag = ""
                if raw_tag:
                    json_match = re.search(r'json:"([^"]+)"', raw_tag)
                    if json_match:
                        json_tag = json_match.group(1)
                
                is_pk = False
                if json_tag == "key" and go_type == "int64":
                    is_pk = True
                    pk_field_info = (field_name, go_type, json_tag)

                fields.append((field_name, go_type, json_tag, is_pk))
    
    if not struct_name or not fields:
        raise ValueError(f"Could not parse 'Record' struct from {file_path}. "
                         "Make sure it's named 'Record' and correctly formatted.")
    if not pk_field_info:
         raise ValueError(f"Could not identify primary key in 'Record' struct. "
                         "Ensure one field of type 'int64' has `json:\"key\"` tag.")

    return package_name, struct_name, fields, pk_field_info

# 3. 生成 Go SQLite 包装器
def generate_go_sqlite_wrapper(original_package, struct_name, fields, pk_field_info, table_name="kv_store", target_package="sqlite"):
    """
    根据解析的结构体信息生成 Go SQLite 包装器代码。
    """
    pk_field_name = pk_field_info[0]
    
    # Extract non-PK fields for INSERT statements
    non_pk_fields = [f for f in fields if not f[3]] # f[3] is is_pk
    
    # List of column names for SQL queries (excluding PK for INSERT)
    all_column_names = [f[0] for f in fields]
    insert_column_names = [f[0] for f in non_pk_fields]

    # List of Go struct fields for Scan/Insert
    all_struct_field_access = [f"record.{f[0]}" for f in fields]
    insert_struct_field_access = [f"record.{f[0]}" for f in non_pk_fields]
    
    # Placeholders for SQL statements
    all_placeholders = ", ".join(["?" for _ in all_column_names])
    insert_placeholders = ", ".join(["?" for _ in insert_column_names])

    # SQL for CreateTable
    create_table_columns = []
    for field_name, go_type, _, is_pk in fields:
        sql_type = GO_SQL_TYPE_MAP.get(go_type, "TEXT") # Default to TEXT if not mapped
        if is_pk:
            create_table_columns.append(f"{field_name} INTEGER PRIMARY KEY AUTOINCREMENT")
        else:
            create_table_columns.append(f"{field_name} {sql_type}")
    create_table_sql_columns = ",\n\t\t\t".join(create_table_columns)

    go_code = f"""// Code generated by generate_sqlite_wrapper.py. DO NOT EDIT.

package {target_package}

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/glebarez/go-sqlite" // SQLite 驱动
)

// Record 结构体用于表示从数据库中读取的记录
// 注意：这个结构体现在定义在 {target_package} 包内部
type {struct_name} struct {{
"""
    for field_name, go_type, json_tag, _ in fields:
        tag_str = f" `json:\"{json_tag}\"`" if json_tag else ""
        go_code += f"\t{field_name} {go_type}{tag_str}\n"
    go_code += f"""}}

// VSQLiteDB 是一个 SQLite 数据库包装器，用于键值存储
type VSQLiteDB struct {{
	db        *sql.DB
	tableName string // 表名
}}

// NewVSQLiteDB 初始化并返回一个新的 VSQLiteDB 实例
// dbPath 是 SQLite 数据库文件的路径
func NewVSQLiteDB(dbPath string, tableName string) (*VSQLiteDB, error) {{
	db, err := sql.Open("sqlite", dbPath)
	if err != nil {{
		return nil, fmt.Errorf("无法打开数据库文件: %w", err)
	}}

	// 尝试连接并验证数据库是否可用
	if err = db.Ping(); err != nil {{
		db.Close() // 确保关闭连接
		return nil, fmt.Errorf("数据库连接失败: %w", err)
	}}

	kvDB := &VSQLiteDB{{
		db:        db,
		tableName: tableName,
	}}

	// 自动创建表
	if err := kvDB.CreateTable(); err != nil {{
		kvDB.Close() // 如果创建表失败，关闭数据库
		return nil, fmt.Errorf("创建表失败: %w", err)
	}}

	// log.Printf("成功连接到 SQLite 数据库: %s", dbPath)
	return kvDB, nil
}}

// Close 关闭数据库连接
func (s *VSQLiteDB) DB() *sql.DB {{
	return s.db
}}

// Close 关闭数据库连接
func (s *VSQLiteDB) Close() error {{
	if s.db != nil {{
		// log.Println("关闭 SQLite 数据库连接...")
		return s.db.Close()
	}}
	return nil
}}

// CreateTable 在数据库中创建键值表
func (s *VSQLiteDB) CreateTable() error {{
	createTableSQL := fmt.Sprintf(`
		CREATE TABLE IF NOT EXISTS %s (
			{create_table_sql_columns}
		);
	`, s.tableName)

	_, err := s.db.Exec(createTableSQL)
	if err != nil {{
		return fmt.Errorf("执行创建表语句失败: %w", err)
	}}
	log.Printf("表 '%s' 已就绪或已创建。", s.tableName)
	return nil
}}

// InsertRecord 将一条记录添加到表中，并返回新生成的自增键。
// record 的 {pk_field_name} 字段会被忽略，因为它是自增的。
func (s *VSQLiteDB) InsertRecord(record {struct_name}) (int64, error) {{
	insertSQL := fmt.Sprintf(`
		INSERT INTO %s ({", ".join(insert_column_names)}) VALUES ({insert_placeholders});
	`, s.tableName)

	result, err := s.db.Exec(insertSQL, {", ".join(insert_struct_field_access)})
	if err != nil {{
		return 0, fmt.Errorf("添加记录失败 (record: %+v): %w", record, err)
	}}

	lastID, err := result.LastInsertId()
	if err != nil {{
		return 0, fmt.Errorf("获取最后插入的ID失败: %w", err)
	}}
	// log.Printf("已添加: {pk_field_name}=%d, record='%+v'", lastID, record)
	return lastID, nil
}}

// GetRecord 根据给定的主键查询其对应的记录
// 如果键不存在，则返回空 Record 和 sql.ErrNoRows 错误
func (s *VSQLiteDB) GetRecord({pk_field_name} int64) ({struct_name}, error) {{
	querySQL := fmt.Sprintf(`SELECT {", ".join(all_column_names)} FROM %s WHERE {pk_field_name} = ?;`, s.tableName)

	var record {struct_name}
	err := s.db.QueryRow(querySQL, {pk_field_name}).Scan({", ".join(all_struct_field_access)})
	if err != nil {{
		if err == sql.ErrNoRows {{
			// log.Printf("查询失败: 键 '%d' 不存在。", {pk_field_name})
			return {struct_name}{"{}"}, err // 返回 sql.ErrNoRows 表示未找到
		}}
		return {struct_name}{"{}"}, fmt.Errorf("查询键 '%d' 失败: %w", {pk_field_name}, err)
	}}
	// log.Printf("查询成功: {pk_field_name}='%d', record='%+v'", {pk_field_name}, record)
	return record, nil
}}

// DeleteRecord 根据给定的主键删除记录
// 如果键不存在，则返回 sql.ErrNoRows 错误。
func (s *VSQLiteDB) DeleteRecord({pk_field_name} int64) error {{
	deleteSQL := fmt.Sprintf(`DELETE FROM %s WHERE {pk_field_name} = ?;`, s.tableName)
	result, err := s.db.Exec(deleteSQL, {pk_field_name})
	if err != nil {{
		return fmt.Errorf("删除键 '%d' 失败: %w", {pk_field_name}, err)
	}}
	rowsAffected, _ := result.RowsAffected()
	if rowsAffected == 0 {{
		// log.Printf("删除操作: 键 '%d' 不存在。", {pk_field_name})
		return sql.ErrNoRows // 如果没有行受影响，表示键不存在
	}} else {{
		// log.Printf("删除成功: 键 '%d'。", {pk_field_name})
	}}
	return nil
}}

// CountRecords 返回表中的记录总数。
func (s *VSQLiteDB) CountRecords() (int64, error) {{
	querySQL := fmt.Sprintf(`SELECT COUNT(*) FROM %s;`, s.tableName)
	var count int64
	err := s.db.QueryRow(querySQL).Scan(&count)
	if err != nil {{
		return 0, fmt.Errorf("获取记录总数失败: %w", err)
	}}
	return count, nil
}}

// MaxKey 返回表中最大的键值。
// 如果表为空，则返回 0 和 sql.ErrNoRows 错误。
func (s *VSQLiteDB) MaxKey() (int64, error) {{
	querySQL := fmt.Sprintf(`SELECT MAX({pk_field_name}) FROM %s;`, s.tableName)
	var maxKey sql.NullInt64 // 使用 sql.NullInt64 来处理空表时 MAX 返回 NULL 的情况
	err := s.db.QueryRow(querySQL).Scan(&maxKey)
	if err != nil {{
		return 0, fmt.Errorf("获取最大键失败: %w", err)
	}}
	if !maxKey.Valid {{
		// 表为空
		return 0, sql.ErrNoRows // 返回 sql.ErrNoRows 表示未找到任何键
	}}
	return maxKey.Int64, nil
}}

// GetRandomRecord 从表中随机读取一条记录。
// 如果表为空，则返回 sql.ErrNoRows 错误。
func (s *VSQLiteDB) GetRandomRecord() ({struct_name}, error) {{
	querySQL := fmt.Sprintf(`SELECT {", ".join(all_column_names)} FROM %s ORDER BY RANDOM() LIMIT 1;`, s.tableName)
	var record {struct_name}
	err := s.db.QueryRow(querySQL).Scan({", ".join(all_struct_field_access)})
	if err != nil {{
		if err == sql.ErrNoRows {{
			return {struct_name}{"{}"}, sql.ErrNoRows // 表中没有记录
		}}
		return {struct_name}{"{}"}, fmt.Errorf("随机查询记录失败: %w", err)
	}}
	return record, nil
}}
"""
    return go_code

# Main function to run the generator
def main():
    parser = argparse.ArgumentParser(description="Generate a Go SQLite wrapper from a Go struct definition.")
    parser.add_argument("input_go_file", help="Path to the Go file containing the struct definition (e.g., bot/record.go).")
    parser.add_argument("--output", "-o", default="sqlite/sqlite.go", help="Output Go file path (default: sqlite/sqlite.go).")
    parser.add_argument("--table-name", "-t", default="my_kv_store", help="Default table name for the SQLite database (default: my_kv_store).")
    parser.add_argument("--package", "-p", default="sqlite", help="Target Go package name for the generated code (default: sqlite).")
    
    args = parser.parse_args()

    input_file = args.input_go_file
    output_file = args.output
    table_name = args.table_name
    target_package = args.package

    try:
        original_package, struct_name, fields, pk_field_info = parse_go_struct(input_file)
        
        # Ensure the output directory exists
        output_dir = os.path.dirname(output_file)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir)

        generated_code = generate_go_sqlite_wrapper(
            original_package, struct_name, fields, pk_field_info, table_name, target_package
        )

        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(generated_code)
        
        print(f"Successfully generated SQLite wrapper for struct '{struct_name}' from '{input_file}' to '{output_file}'")
        print(f"Remember to run 'gofmt -w {output_file}' to format the generated code.")

    except ValueError as e:
        print(f"Error: {e}")
    except FileNotFoundError:
        print(f"Error: Input file '{input_file}' not found.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()